"""
A data class for items in the repository API
"""

from dataclasses import asdict, dataclass, field
from jupyterfair.core.connection import Connection

@dataclass
class Item:
    """Data class for an Item in the data repository"""
    name: str
    item_id: str = None
    remote_url: str = None

    def __call__(self) -> dict:
        """
        Returns class attributes as a dictionary
        """
        return asdict(self)

    def set_item_id(self, item_id: str) -> None:
        """ Sets the value for attribut 'item_id'
        
        params:
            item_id: identifier generated by the data repository API
        """

        self.item_id = item_id
        
        return None

    def set_item_id(self, remote_url: str) -> None:
        """ Sets the value of the remote_url attribute
        
        params:
            remote_url: url to the item generated by the data repository API
        """

        self.item_id = remote_url
        
        return None

    def upload_file(self, connection: Connection, file: str ) -> None:
        """
        Uploads a file attached to an item to a data repository

        params:
            connection: a instance of a Connection class to a data repository
            file: path to the file to be uploaded

        returns:
            
        """
        pass



if __name__ == '__main__':
    name =  'my article'

    item = Item(name)

    print(item())

    

    
